export default placementArray = [
    {},
    {value: 7, onClick: insertNumber},
    {value: 8, onClick: insertNumber},
    {value: 9, onClick: insertNumber},
    {value: 'DEL', onClick: del},
    {value: 'AC', onClick: clearCalculator},
    {},
    {value: 4, onClick: insertNumber},
    {value: 5, onClick: insertNumber},
    {value: 6, onClick: insertNumber},
    {value: '*', onClick: insertOperator},
    {value: '/', onClick: insertOperator},
    {},
    {value: 1, onClick: insertNumber},
    {value: 2, onClick: insertNumber},
    {value: 3, onClick: insertNumber},
    {value: '+', onClick: insertOperator},
    {value: '-', onClick: insertOperator},
    {},
    {value: 0, onClick: insertNumber},
    {value: '.', onClick: insertDot},
    {value: '(', onClick: insertOpenBracket},
    {value: ')', onClick: insertCloseBracket},
    {value: '=', onClick: equal},
];